# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=1000, null=True)),
                ('street1', models.CharField(max_length=1000, null=True)),
                ('street2', models.CharField(max_length=1000, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('cik', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('stateincorp', models.CharField(max_length=2, null=True)),
                ('irsnum', models.IntegerField(null=True)),
                ('classification', models.CharField(max_length=200, null=True)),
                ('fiscal_yearend', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NonDerivative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('security', models.CharField(max_length=50)),
                ('owner_istenpercentowner', models.CharField(default=0, max_length=1)),
                ('owner_sharesownedfollowingtransaction', models.IntegerField()),
                ('code', models.CharField(max_length=1)),
                ('formtype', models.PositiveSmallIntegerField()),
                ('isequityswap', models.CharField(default=0, max_length=1)),
                ('shares', models.IntegerField()),
                ('ownershipnature', models.CharField(max_length=1)),
                ('pricepershare', models.TextField()),
                ('acqdisp_code', models.CharField(max_length=1)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_filings.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=1000, null=True)),
                ('street1', models.CharField(max_length=1000, null=True)),
                ('street2', models.CharField(max_length=1000, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('zipcode', models.CharField(max_length=10, null=True)),
                ('cik', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('isdirector', models.PositiveSmallIntegerField()),
                ('isofficer', models.PositiveSmallIntegerField()),
                ('officertitle', models.CharField(max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='nonderivative',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sec_filings.Owner'),
        ),
    ]
