# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_filings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonderivative',
            name='isequityswap',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='nonderivative',
            name='owner_istenpercentowner',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
