# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_filings', '0002_auto_20170914_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonderivative',
            name='accession_num',
            field=models.CharField(default='NotCaptured', max_length=20),
            preserve_default=False,
        ),
    ]
