# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_filings', '0003_nonderivative_accession_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonderivative',
            name='security',
            field=models.CharField(max_length=100),
        ),
    ]
