# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sec_filings', '0004_auto_20170921_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticker',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
